### ISSUE TITLE
[META] Executing a proof-of-concept (POC) implementation as outlined in the project proposal.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-metrics#6]
### Proposal POC implementation
Coming from the proposal https://github.com/opensearch-project/opensearch-health/issues/5 
- [x] Initial git initialization with basic code checkin. (https://github.com/opensearch-project/opensearch-health/pull/2)
- [x] POC implementation based on the [proposal](https://github.com/opensearch-project/opensearch-health/issues/5). (https://github.com/opensearch-project/opensearch-health/pull/4)
   - [x] CDK infrastructure code. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/infrastructure)
      - [x] Deploy Secure OpenSearch cluster in a secure VPC. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/stacks/opensearch.ts)
      - [x] Lambda with zip (to package all the dependencies). [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/constructs/lambda.ts)
      - [x] Restricted IAM roles. 
      - [x] Secure Cognito setup for OpenSearch cluster. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/constructs/opensearchCognito.ts)
      - [x] Nginx proxy to access OpenSearch Dashboard. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/constructs/opensearchNginxProxyCognito.ts)
   - [x] Gradle Setup
      - [x] Project dependencies. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/build.gradle)
      - [x] Task to build both zip (with fat jar having along all runtime dependencies) and jar. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/build.gradle#L44)
   - [x] Lambdas with Dagger Dependency Injection. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/dagger)
   - [x] OpenSearch Util: Rest level client. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/src/main/java/org/opensearchmetrics/dagger/CommonModule.java)
      - [x] Dagger Setup to load the java rest level client. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/src/main/java/org/opensearchmetrics/dagger/CommonModule.java#L61)
      - [x] Client using Secure sigv4 to communicate with cluster. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/src/main/java/org/opensearchmetrics/dagger/CommonModule.java#L61-L70)
      - [x] Client setup for bulk index operations. [link](https://github.com/opensearch-project/opensearch-metrics/blob/main/src/main/java/org/opensearchmetrics/util/OpenSearchUtil.java)
   - [x] Themes and Factors [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/metrics)
      - [x] Re-usable code to load the themes, factors and its thresholds with interface implementation. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/lambda)
      - [x] The implementation should create right search query, search request and perform search on OpenSearch to get the desired values for a theme and factor. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/metrics)
       - [x] Interface implementation of logic for Themes and Factors.
   - [x] Health data POJO Model. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/model)
       - [x] Right Data Model with fields to serialize and deserialize the final data interpreted by the application logic. [link](https://github.com/opensearch-project/opensearch-metrics/tree/main/src/main/java/org/opensearchmetrics/model)
   - [x] Frontend deployment 
       - [x] CDK code to deploy the frontend server, running [frontend CDK Stacks](https://github.com/opensearch-project/opensearch-metrics/tree/main/infrastructure).
       - [x] Secure private server to run POST/GET all on Amazon OpenSearch with sigv4. [aws-observability/aws-sigv4-proxy](https://github.com/opensearch-project/opensearch-metrics/blob/main/infrastructure/lib/stacks/opensearchNginxProxyReadonly.ts).

**Comment by prudhvigodithi** [comment]
Closing this issue as the associated issues part of the description are completed to roll out the metrics project. 
Thank you 
@getsaurabh02
